name: Terraform Drift Detection Pipeline

on:
  schedule:
    - cron: 0 6 * * * # every night at 6:00 am
  workflow_dispatch:

#Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: read
  issues: write

jobs:
  terraform-drift-test:
    name: "Test"
    uses: "Sopra-Steria-Code-Academy/Samling-1-Templates/.github/workflows/terraform-drift-template.yml@main"
    with:
      environment-name: 'test'
    secrets:
      client-id: ${{ secrets.TF_AZURE_CLIENT_ID }}
      subscription-id: ${{ secrets.TF_AZURE_SUBSCRIPTION_ID }}
      tenant-id: ${{ secrets.TF_AZURE_TENANT_ID }}