name: Terraform Plan and Apply

on:
  push:
    branches: [ "master","instructor" ]
    paths:
      - '**/terraform/**'
  pull_request:
    branches: [ "master","instructor" ]
    paths:
      - '**/terraform/**'
  workflow_dispatch:

#Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform-plan-apply-test:
    name: "Test2"
    uses: "Sopra-Steria-Code-Academy/Samling-1-Templates/.github/workflows/terraform-plan-apply-template.yml@main"
    with:
      environment-name: 'test'
    secrets:
      client-id: ${{ secrets.TF_AZURE_CLIENT_ID }}
      subscription-id: ${{ secrets.TF_AZURE_SUBSCRIPTION_ID }}
      tenant-id: ${{ secrets.TF_AZURE_TENANT_ID }}